### ISSUE TITLE
Error while training classification model: No such file or directory: 'meta_data/val.txt'

### ISSUE THREAD

**Issue by MuajiiTsai** [OpenGVLab/InternImage#122]
Similar to #48, the difference is my program built train dataset successfully but failed when building val/test dataset.
```
...
local rank 0 / global rank 0successfully build train dataset
Traceback (most recent call last):
  File "main.py", line 661, in <module>
    main(config)
  File "main.py", line 170, in main
    data_loader_val, data_loader_test, mixup_fn = build_loader(config)
  File "/home/chtsai/InternImage/classification/dataset/build.py", line 64, in build_loader
    dataset_val, _ = build_dataset('val', config=config)
  File "/home/chtsai/InternImage/classification/dataset/build.py", line 216, in build_dataset
    dataset = ImageCephDataset(root, 'val', transform=transform)
  File "/home/chtsai/InternImage/classification/dataset/cached_image_folder.py", line 313, in __init__
    on_memory=on_memory)
  File "/home/chtsai/InternImage/classification/dataset/cached_image_folder.py", line 383, in __init__
    with open(osp.join(annotation_root, f'{split}.txt'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'meta_data/val.txt'
```

**Comment by Zeqiang-Lai** [comment]
[val.txt](https://github.com/OpenGVLab/InternImage/files/11300199/val.txt)

Here it is.

**Comment by MuajiiTsai** [comment]
But I use the first method to prepare data, not the zip ImageNet method. Do I still need to add train.txt or val.txt in my ./metadata/?

**Comment by Zeqiang-Lai** [comment]
Yes, you probably need the train.txt and val.txt if you are using ImageCephDataset, otherwise, you might have to change the val dataset to use torchvision datasets as well.

You could try to download the metadata train.txt here

https://github.com/Zeqiang-Lai/InternImage/releases/tag/1.0

**Comment by MuajiiTsai** [comment]
OK, I'll give it a try. Thanks!

**Comment by NagacharanVemula** [comment]
Hey @Zeqiang-Lai what if i want to train InternImage on a new dataset? Do I have to create these train.txt and val.txt for the new dataset?
