### ISSUE TITLE
请问win10用户如何编译以及使用DCNv3算子

### ISSUE THREAD

**Issue by yanxin12** [OpenGVLab/InternImage#145]
![图片](https://github.com/OpenGVLab/InternImage/assets/50025572/fbc7dd78-7550-41ae-b3f2-9639d8524826)
![图片](https://github.com/OpenGVLab/InternImage/assets/50025572/e981ba9c-8337-4029-97ba-9470ac3f71e7)
我也是win10用户，使用sh指令编译处理DCNv3的pyd文件，但在dcnv3_func.py文件中就是没办法导入，你们提供的whl文件
好像只支持linux系统，可以提供win10系统的吗

**Comment by Hanzc989** [comment]
估计你编译出问题了,

**Comment by lucyfighting** [comment]
我看工程里没有windows的安装包，我只找到linux的。同问这个问题

**Comment by Heart-Sniper** [comment]
请问楼主现在解决这个问题了吗，have same question， 悲

**Comment by zxbzhineng** [comment]
我的CUDA版本为11.7，编译成功，用命令python setup.py build install替代命令sh ./make.sh

**Comment by zxbzhineng** [comment]
> 我看工程里没有windows的安装包，我只找到linux的。同问这个问题


我的CUDA版本为11.7，编译成功，用命令python setup.py build install替代命令sh ./make.sh
> 我看工程里没有windows的安装包，我只找到linux的。同问这个问题

**Comment by SrzAyl** [comment]
> 我的CUDA版本为11.7，编译成功，用命令python setup.py build install替代命令sh ./make.sh

求问是只有11.7版本的cuda能编译吗，我11.3就不行，悲

**Comment by zxbzhineng** [comment]
应该是这样的，我之前也试过别的CUDA版本，编译就会失败，换成11. 7编译就成功了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月2日(周二) 上午8:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OpenGVLab/InternImage] 请问win10用户如何编译以及使用DCNv3算子 (Issue #145)




  
我的CUDA版本为11.7，编译成功，用命令python setup.py build install替代命令sh ./make.sh
  
求问是只有11.7版本的cuda能编译吗，我11.3就不行，悲

**Comment by ENMA9527** [comment]
> 我的CUDA版本为11.7，编译成功，用命令python setup.py build install替代命令sh ./make.sh

你好，请问是C++版本才需要编译吗？如果我使用pytorch版本的话是不是就不用编译
