### ISSUE TITLE
AssertionError: The `num_classes` (3) in DINOHead of MMDataParallel does not matches the length of `CLASSES` 80) in CocoDataset

### ISSUE THREAD

**Issue by dinhthihuyen** [OpenGVLab/InternImage#147]
I run detection algorithm for a dataset with 3 classes using model dino_4scale_internimage_t_1x_coco_layer_wise_lr.py, I got this error "AssertionError: The `num_classes` (3) in DINOHead of MMDataParallel does not matches the length of `CLASSES` 80) in CocoDataset".
How can I fix that?
Thanks so much for your support!.

**Comment by dinhthihuyen** [comment]
I found out the solutions, add classes=classes in config file

**Comment by chenzx2** [comment]
> I found out the solutions, add classes=classes in config file

I got the same problem,  how to add classes=classes in config file?
