### ISSUE TITLE
同样的问题缺失val.txt

### ISSUE THREAD

**Issue by LH1222** [OpenGVLab/InternImage#163]
您好，与之前的问题一样，我也采用了classification里第一种数据集方式，出现了同样的缺失问题。
那么，我如果想继续用第一种方式，需要做出哪些改变？还是说，必须更改我的数据集形式。

**Comment by LH1222** [comment]
我找到解决办法了，在classification/dataset/build.py中将[L210-L216](https://github.com/OpenGVLab/InternImage/blob/master/classification/dataset/build.py#L210-L216)替换
`            dataset = CachedImageFolder(root, transform=transform)
        elif prefix == 'val':
            root = os.path.join(config.DATA.DATA_PATH, 'val')
            dataset = CachedImageFolder(root, transform=transform)`

**Comment by jeonga0303** [comment]
Your solution was helpful.

tip
`from .cached_image_folder import ImageCephDataset, CachedImageFolder`
