### ISSUE TITLE
Can't you infer the image file itself from the inference_detector function?

### ISSUE THREAD

**Issue by jeonga0303** [OpenGVLab/InternImage#175]
First of all, you can use the following methods to infer.
`image = PIL.Image.open(image)`
`image = np.array(image)`
`result = inference_detector(model, image)`

However, it results in a different result than when inferred through the file path and when the image is inserted. Correct results appear when inferring from file path

The reason is that when inferring the image file itself, the preprocessing process must be performed manually.
<img width="617" alt="image" src="https://github.com/OpenGVLab/InternImage/assets/52391624/1f7be456-d35b-46b9-9426-2fc370f7fa79">

So I implemented the pre-processing code myself.
transforms.Methods such as Compose are not supported in the mmcv subversion.

But now it's a problem. After implementing preprocessing similarly, I put a value in the function and found the following error.
<img width="586" alt="image" src="https://github.com/OpenGVLab/InternImage/assets/52391624/f3d2a921-2d45-4cfb-a8eb-04f998c5c4c3">
`TypeError: expected str, bytes or os.PathLike object, not Tensor`

Do you know how to recall and infer images themselves?
Pre-processing must be included. Please provide the sample code at least.

**Comment by chungminho1** [comment]
죄송하지만 모델 빌드는 init_detector 사용하셨나요? 저는 거기부터 막혀서ㅠㅠ

**Comment by jeonga0303** [comment]
> 죄송하지만 모델 빌드는 init_detector 사용하셨나요? 저는 거기부터 막혀서ㅠㅠ

음,, internimage 모델 사용하실거면 internimage 레포지토리 중 detection 폴더가 있어야합니다
하위 폴더 중 configs, mmcv_custom, mmdet_custom, ops_dcnv3, tools는 무조건 있어야돼요
그리고 docker로 python랑 mmcv 환경 조성하시고, ops_dcnv3 이용해서 DCNv3 모듈 설치 된 환경이어야해요

init_detector 사용해서 inference 하실 때는 이런식으로 진행하시면 됩니다~ 문제없이 잘 작동해요
<img width="530" alt="image" src="https://github.com/OpenGVLab/InternImage/assets/52391624/2a19414c-795e-4223-84bc-ab0acdf307a0">

**Comment by chungminho1** [comment]
감사합니다!!

**Comment by jeonga0303** [comment]
This issue has been resolved.

To infer the image itself, you can preprocess it as follows.
`image = mmcv.imread('xxxx.jpg')`

The results are the same as when deducing by file path.

And if you want to deduce using a byte-type image, please refer to the following.
`image = mmcv.imfrombytes(image, flag='color'`
`image = mmcv.imread(image)`

**Comment by Dai23** [comment]
> > 죄송하지만 모델 빌드는 init_detector 사용하셨나요? 저는 거기부터 막혀서ㅠㅠ
> 
> 음,, internimage 모델 사용하실거면 internimage 레포지토리 중 detection 폴더가 있어야합니다 하위 폴더 중 configs, mmcv_custom, mmdet_custom, ops_dcnv3, tools는 무조건 있어야돼요 그리고 docker로 python랑 mmcv 환경 조성하시고, ops_dcnv3 이용해서 DCNv3 모듈 설치 된 환경이어야해요
> 
> init_detector 사용해서 inference 하실 때는 이런식으로 진행하시면 됩니다~ 문제없이 잘 작동해요 <img alt="image" width="530" src="https://private-user-images.githubusercontent.com/52391624/242182471-2a19414c-795e-4223-84bc-ab0acdf307a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTQ1MDksIm5iZiI6MTczMzIxNDIwOSwicGF0aCI6Ii81MjM5MTYyNC8yNDIxODI0NzEtMmExOTQxNGMtNzk1ZS00MjIzLTg0YmMtYWIwYWNkZjMwN2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA4MjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MDdlZTZmM2Y3OTk4MTI1M2FmZWYwZGIwYWEwYzk4ZmZkN2M5MzliNjg0ZmZkMTc1OGRlN2U3MzhmMjUwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KImQymza5dqpmJCvTIUqsjoYRaD_2ImIi2ekoF0dB78">

When you run to model=init_detector (configpath, model_death, device=device), won't you get an error? No matter which object detection model I run, I always get the following error: KeyError: "MaskRCNN: 'InternImage is not in the models registry', and the model never appears in the registry.
