### ISSUE TITLE
To trt model have problem!

### ISSUE THREAD

**Issue by xuweidongkobe** [OpenGVLab/InternImage#180]
I have built the trt plugins and load successfully.  I use the following code to transfer torch model to trt model,  the onnx model has benn transferred successfully, but trt model have problem.

python deploy.py "./deploy/configs/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py" "./configs/coco/cascade_internimage_xl_fpn_1x_coco.py" "./models/cascade_internimage_xl_fpn_1x_coco.pth" "./deploy/demo.jpg" --work-dir "./trt_model/" --device cuda --dump-info

<img width="543" alt="problem" src="https://github.com/OpenGVLab/InternImage/assets/25764883/31755c5e-818e-4a7c-9edb-2795718a2d7f">

I tried using different versions of onnx, but it still hasn't been resolved. The trt version is 8.2.3.0. Can you give me some advice？ Thanks.

**Comment by j0987834204** [comment]
I upgraded TensorRT version to solve the problem.

**Comment by xuweidongkobe** [comment]
> I upgraded TensorRT version to solve the problem.

hi，can you tell me which trt version you used?

**Comment by xuweidongkobe** [comment]
@j0987834204

**Comment by xuweidongkobe** [comment]
I solved the problem with Tensort v8.6.1.6.
