### ISSUE TITLE
How to train baseline for OpenLane-V2 Challenge?

### ISSUE THREAD

**Issue by josh081823** [OpenGVLab/InternImage#205]
The file "./tools/dist_train.sh" mentioned in the command ["./tools/dist_train.sh plugin/mmdet3d/configs/internimage-s.py 8"](https://github.com/OpenGVLab/InternImage/tree/master/autonomous_driving/openlane-v2#3-train-with-internimage-small)  is not found in the directory "InternImage/autonomous_driving/openlane-v2/". 

How can I train this model?

**Comment by czczup** [comment]
https://github.com/OpenGVLab/InternImage/tree/master/autonomous_driving/openlane-v2
Hi, it has been updated.

**Comment by josh081823** [comment]
> https://github.com/OpenGVLab/InternImage/tree/master/autonomous_driving/openlane-v2 Hi, it has been updated.

Thank you very much for your reply!
