### ISSUE TITLE
Interest in adapating InternImage for 3D segmentation

### ISSUE THREAD

**Issue by ricklisz** [OpenGVLab/InternImage#23]
Hi, I am very interested in your work! I am wondering if it'd be possible to adapt this backbone for 3D segmentation tasks? Any advice would be great. Thank you!

**Comment by czczup** [comment]
Hi, thank you for showing interest in my work! In regard to your question, I think it could be a good attempt. However, as I am unsure about the backbone architecture needed for 3D segmentation tasks, I suggest you consult domain experts for more constructive advice. I hope this helps, thank you!
