### ISSUE TITLE
ATen/OpMathType.h no such file or dictionary.

### ISSUE THREAD

**Issue by fanrena** [OpenGVLab/InternImage#25]
Trying to compile DCNv3 with PyTorch 1.9.0. and the compiler give me this error. After checking pytorch code in github, it appears that OpMathType.h were added after PyTorch 1.10. But the Readme.md in detection folder says pytorch >= 1.8.0.  Or there is a solution for my error? Im not sure.

**Comment by fanrena** [comment]
Can I just copy OpMathType.h into my pytorch include folder? Im pretty much new in C++ & PyTorch.

**Comment by QichenZheng** [comment]
Changing the pytorch version to 1.12.0 can solve this problem.

**Comment by fanrena** [comment]
> Changing the pytorch version to 1.12.0 can solve this problem.

Thank you! But as I mentioned in my description, Pytorch >= 1.8.0 would be wrong as described in readme.md if higher version of pytorch is required. Can you give a more precise border line for pytorch in readme. Thanks again for your excellent work.

**Comment by czczup** [comment]
Thanks for your reply, we will fix this issue.
