### ISSUE TITLE
About the stride in detection/ops_dcnv3

### ISSUE THREAD

**Issue by GoblinCraftman** [OpenGVLab/InternImage#258]
I found that in detection/ops_ In the Pytorch version of dcnv3, the calculation of offset does not consider the stride, and the side is specified as 1 in the test code.

When we attempted to calculate using a stride of 2, there was a conflict between the size of the unstriped matrix obtained by offset and the size of the scaled matrix obtained by the stride 2. The error matrix size would be exactly twice that of this time.

The final code error will be:

Sampling_ Locations=(ref+grid * offset_scale). repeat (N_, 1, 1, 1, 1). flat (3,4)+\
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (x) must match the size of tensor b (2x) at non-singleton dimension 2

I want to know: Is it the code that does not recommend using non 1 stride or is there an error handling at offset?

**Comment by baic9120** [comment]
hello, have you solved this problem？look forward to your answer, thanks!!

**Comment by YanjunPen** [comment]
hello, I also have this problem, have you do anything to solve it?
