### ISSUE TITLE
potential error of segmentation config (base model) ?

### ISSUE THREAD

**Issue by fuqianya** [OpenGVLab/InternImage#27]
Hi Authors,

Thanks for your great work! I noticed that the `num_layers` in the config of base model [upernet_internimage_b_512_160k_ade20k.py](https://github.com/OpenGVLab/InternImage/blob/master/segmentation/configs/upernet/upernet_internimage_b_512_160k_ade20k.py#L53) is inconsistent with the `depths` in [upernet_internimage_b_512_160k_ade20k.py](https://github.com/OpenGVLab/InternImage/blob/master/segmentation/configs/upernet/upernet_internimage_b_512_160k_ade20k.py#L17). However, these two parameters are consistent in other variants (e.g., tiny, small, large). Is this a specific configuration of the base model or is it human error？

**Comment by czczup** [comment]
> Hi Authors,
> 
> Thanks for your great work! I noticed that the `num_layers` in the config of base model [upernet_internimage_b_512_160k_ade20k.py](https://github.com/OpenGVLab/InternImage/blob/master/segmentation/configs/upernet/upernet_internimage_b_512_160k_ade20k.py#L53) is inconsistent with the `depths` in [upernet_internimage_b_512_160k_ade20k.py](https://github.com/OpenGVLab/InternImage/blob/master/segmentation/configs/upernet/upernet_internimage_b_512_160k_ade20k.py#L17). However, these two parameters are consistent in other variants (e.g., tiny, small, large). Is this a specific configuration of the base model or is it human error？

Thanks for your feedback, it is an error, and I will fix it.  

But don't worry, it won't hurt performance. Because the `depths` affects the learning rate of different layers only when the layer-wise learning rate is turned on, it will not take effect as `layer_decay_rate` is set to 1.0.


```
optimizer = dict(
    _delete_=True, type='AdamW', lr=0.00006, betas=(0.9, 0.999), weight_decay=0.05,
    constructor='CustomLayerDecayOptimizerConstructor',
    paramwise_cfg=dict(num_layers=30, layer_decay_rate=1.0,
                       depths=[4, 4, 18, 4]))
```
