### ISSUE TITLE
Typo in classification/meta_data/map22kto1k.txt?

### ISSUE THREAD

**Issue by ZhiqiGao2001** [OpenGVLab/InternImage#278]
Hello! 
Thanks for the open-source model, I am doing some research on it and find a possible typo

![image](https://github.com/OpenGVLab/InternImage/assets/61210089/26c10615-0054-4ffc-9c50-e4e7f7afb19a)
I think there should not be a duplicate in the mapping. The wrong one (number 850) should be [n04399382: teddy bear] from what I see in the other metadata file in the Imagenet-1k repo? (but n04399382 does not exist in the 22k_class_to_idx.json?)

**Comment by EasonXiao-888** [comment]
@ZhiqiGao2001  I wonder to know how you solved it. Looking forward to your reply
