### ISSUE TITLE
I don't understand this shared weight in the article, can you explain it in detail, please?

### ISSUE THREAD

**Issue by JavanTang** [OpenGVLab/InternImage#3]
> To remedy this problem, we borrow the idea from the separable convolution [56] and detach the original convolution weights wk into depth-wise and point-wise parts, where the depth-wise part is responsible by the original location-aware modulation scalar mk, and the point-wise part is the shared projection weights w among sampling points.

Can you provide some information? Thank you very much!

**Comment by whai362** [comment]
For example, a 3 * 3 convolution needs 9 different linear projection weights. The shared weights mean that the 9 linear projections have the same weights.
