### ISSUE TITLE
Pure Python implemented DCNv3 ?

### ISSUE THREAD

**Issue by edwardyehuang** [OpenGVLab/InternImage#41]
Could you provide pure Python/PyTorch implemented DCNv3? It will be easier to migrate and run on a Non-CUDA device.

**Comment by czczup** [comment]
Hi, thanks for your attention. We have implemented pure pytorch version DCNv3, for example, you can see the `DCNv3_pytorch` class in this [code](https://github.com/OpenGVLab/InternImage/blob/master/detection/ops_dcnv3/modules/dcnv3.py).

If you want to use `DCNv3_pytorch` in downstream tasks, such as object detection and semantic segmentation, you can replace the `core_op='DCNv3'` with `core_op='DCNv3_pytorch'`.

```
model = dict(
    backbone=dict(
        _delete_=True,
        type='InternImage',
        core_op='DCNv3_pytorch',
        channels=160,
        depths=[5, 5, 22, 5],
        groups=[10, 20, 40, 80],
        mlp_ratio=4.,
```

**Comment by edwardyehuang** [comment]
Thanks. One of the most significant works in computer vision, btw.
