### ISSUE TITLE
如何体验或测试“图文检索”能力

### ISSUE THREAD

**Issue by huifeiyang** [OpenGVLab/InternImage#49]
您好，目前公开的能力中，仅提供了图像检测、分类、分割任务方向。
在介绍中包括了“图文检索”能力，请问如何测试体验？

**Comment by whai362** [comment]
可以参考Uni-Perceiver、Uni-Perceiver-MoE、Uni-Perceiver v2

**Comment by huifeiyang** [comment]
> 可以参考Uni-Perceiver、Uni-Perceiver-MoE、Uni-Perceiver v2

感谢
我理解的多模大模型应该是一个模型来解决多类任务，请教后期有类似的规划么？

**Comment by ottolu** [comment]
> > 可以参考Uni-Perceiver、Uni-Perceiver-MoE、Uni-Perceiver v2
> 
> 感谢 我理解的多模大模型应该是一个模型来解决多类任务，请教后期有类似的规划么？

感谢关注，敬请期待项目后续更新

**Comment by huifeiyang** [comment]
感谢解惑
