### ISSUE TITLE
Running code with cpu instead of cuda

### ISSUE THREAD

**Issue by ThaiHuyen** [OpenGVLab/InternImage#53]
I have error install cuda to run code. Could I run it with cpu instead? I found out folder cpu and cuda in folder src in code but not sure how to switch to run code with cpu? Thanks so much for your support.

**Comment by czczup** [comment]
Hi, thanks for your attention. You can replace `core_op='DCNv3'` with  `core_op='DCNv3_pytorch'`, that is a pure pytorch implementation of DCNv3.

Example:
```
backbone=dict(
        _delete_=True,
        type='InternImage',
        core_op='DCNv3_pytorch', # see here
        channels=112,
        depths=[4, 4, 21, 4],
        groups=[7, 14, 28, 56],
        mlp_ratio=4.,
        drop_path_rate=0.4,
        norm_layer='LN',
        layer_scale=1.0,
        offset_scale=1.0,
        post_norm=True,
        with_cp=False,
        out_indices=(0, 1, 2, 3),
        init_cfg=dict(type='Pretrained', checkpoint=pretrained)),
```

**Comment by dinhthihuyen** [comment]
Thank you!

**Comment by dinhthihuyen** [comment]
I implemented DINO for Object detection and get the errors "AssertionError("Torch not compiled with CUDA enabled"), although I changed core_op='DCNv3_pytorch' in file dino_4scale_internimage_t_1x_coco_layer_wise_lr_copy.py. How could I fix that?
