### ISSUE TITLE
Mismatch of configuration files in Cityscapes Segmentation

### ISSUE THREAD

**Issue by sd-OFF** [OpenGVLab/InternImage#57]
There seems to mismatch of configuration in cityscapes's segmentation folder. I am getting resnetback bone from InternImage XL model and There are some missing keys in the checkpoint file. please check it

**Comment by czczup** [comment]
> There seems to mismatch of configuration in cityscapes's segmentation folder. I am getting resnetback bone from InternImage XL model and There are some missing keys in the checkpoint file. please check it

Hi, thanks for your feedback. Could you share me the log of missing keys?

**Comment by sd-OFF** [comment]
Other than backbone, the rest are from auxiliary head and decode head due to number of classes.
