### ISSUE TITLE
DCNV3安装遇到的问题

### ISSUE THREAD

**Issue by CuZaoo** [OpenGVLab/InternImage#60]
你好，我这里遇到了以下问题
1.直接使用 sh ./make.sh命令会出现以下错误
![image](https://user-images.githubusercontent.com/39364400/226624194-6199f718-a701-4de4-8393-7252e544a79d.png)
2.我查看了make.sh命令发现只是以下的python命令，所以我直接运行了该命令，但是又出现了以下错误。
![image](https://user-images.githubusercontent.com/39364400/226624601-33d6d26c-c97f-400b-916c-83b0c327a235.png)
我的cuda路径确实是这里
![image](https://user-images.githubusercontent.com/39364400/226625369-4b4010e3-227c-455a-a6ad-0b70664a599a.png)
从报错的地方看，好像路径的前边多了一个:，但是我对相关代码不熟悉，找不出报错的地方。
不知道有没有好的解决方法
谢谢

**Comment by 1nancy23** [comment]
作者最里面那个functions给的dcn3_func.py

> 你好，我这里遇到了以下问题 1.直接使用 sh ./make.sh命令会出现以下错误 ![image](https://user-images.githubusercontent.com/39364400/226624194-6199f718-a701-4de4-8393-7252e544a79d.png) 2.我查看了make.sh命令发现只是以下的python命令，所以我直接运行了该命令，但是又出现了以下错误。 ![image](https://user-images.githubusercontent.com/39364400/226624601-33d6d26c-c97f-400b-916c-83b0c327a235.png) 我的cuda路径确实是这里 ![image](https://user-images.githubusercontent.com/39364400/226625369-4b4010e3-227c-455a-a6ad-0b70664a599a.png) 从报错的地方看，好像路径的前边多了一个:，但是我对相关代码不熟悉，找不出报错的地方。 不知道有没有好的解决方法 谢谢

作者给的functions文件夹里面dcnv3_func.py里面有个import DCNv3根本没有

**Comment by ChaseMonsterAway** [comment]
Checking the environment variable may be helpful.

**Comment by czczup** [comment]
> 

你好，这里需要重新设置一下CUDA的Path，然后重新编译一下。

**Comment by YeShenglong1** [comment]
我们今天会放出预编译的whl包，欢迎关注

**Comment by yukeyiniupi** [comment]
> 我们今天会放出预编译的whl包，欢迎关注

你好，DCNv3 预编译的whl包放出了吗？

**Comment by YeShenglong1** [comment]
已放出，请关注最新的release

**Comment by zhangjin10** [comment]
> 已放出，请关注最新的release

请问有没有windows的安装包？

**Comment by czczup** [comment]
预编译的whl包见这里：https://github.com/OpenGVLab/InternImage/releases/tag/whl_files

**Comment by WangJ0412** [comment]
no windows whl

**Comment by TTiannaiTT** [comment]
这个报错应该是因为文件的类型是dos,更改为unix即可正常运行这个脚本，我用vim修改了之后就能跑了
