### ISSUE TITLE
Bad substitution when training on COCO

### ISSUE THREAD

**Issue by dinhthihuyen** [OpenGVLab/InternImage#67]
I train detection model on COCO following README.md: 
sh dist_train.sh configs/mask_rcnn/mask_rcnn_internimage_t_fpn_1x_coco.py 8
and get Error: dist_train.sh: 7: dist_train.sh: Bad substitution

**Comment by czczup** [comment]
You could try `bash` instead of `sh`.

**Comment by dinhthihuyen** [comment]
Thanks
