### ISSUE TITLE
how to change batch_size?

### ISSUE THREAD

**Issue by jeonga0303** [OpenGVLab/InternImage#69]
RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB

There is a problem running the code. 
Can I know where to change the batch size?

**Comment by jeonga0303** [comment]
If you want to adjust the batch size, please adjust the samples_per_gpu in the configs/model. 
samples_per_gpu means batch size per GPU card.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/52391624/228466217-a3352f58-0554-4b59-845c-82169e7a196d.png">

But I'm still running out of GPU memory. 
If you have any tips for saving GPU memory, please share them.

**Comment by czczup** [comment]
> If you want to adjust the batch size, please adjust the samples_per_gpu in the configs/model. samples_per_gpu means batch size per GPU card.
> 
> <img alt="image" width="406" src="https://user-images.githubusercontent.com/52391624/228466217-a3352f58-0554-4b59-845c-82169e7a196d.png">
> 
> But I'm still running out of GPU memory. If you have any tips for saving GPU memory, please share them.

Hi, thanks for your feedback. May I ask how much GPU memory do you have?
You can try set `with_cp=True` in the config to save training memory.

**Comment by jeonga0303** [comment]
> > If you want to adjust the batch size, please adjust the samples_per_gpu in the configs/model. samples_per_gpu means batch size per GPU card.
> > <img alt="image" width="406" src="https://user-images.githubusercontent.com/52391624/228466217-a3352f58-0554-4b59-845c-82169e7a196d.png">
> > But I'm still running out of GPU memory. If you have any tips for saving GPU memory, please share them.
> 
> Hi, thanks for your feedback. May I ask how much GPU memory do you have? You can try set `with_cp=True` in the config to save training memory.

thank you for your reply.
My GPU memory is using two, and each available memory is about 10GB 
`with_cp=True` is very good advice. 😁

**Comment by Italian-PAO** [comment]
> > If you want to adjust the batch size, please adjust the samples_per_gpu in the configs/model. samples_per_gpu means batch size per GPU card.
> > <img alt="image" width="406" src="https://user-images.githubusercontent.com/52391624/228466217-a3352f58-0554-4b59-845c-82169e7a196d.png">
> > But I'm still running out of GPU memory. If you have any tips for saving GPU memory, please share them.
> 
> Hi, thanks for your feedback. May I ask how much GPU memory do you have? You can try set `with_cp=True` in the config to save training memory.

Thanks a lot!
`with_cp=True` works for InternImage-T with a 12GB memory GPU
And may I ask how it works?
Thanks again : )

**Comment by KevinXu-01** [comment]
> > If you want to adjust the batch size, please adjust the samples_per_gpu in the configs/model. samples_per_gpu means batch size per GPU card.
> > <img alt="image" width="406" src="https://user-images.githubusercontent.com/52391624/228466217-a3352f58-0554-4b59-845c-82169e7a196d.png">
> > But I'm still running out of GPU memory. If you have any tips for saving GPU memory, please share them.
> 
> Hi, thanks for your feedback. May I ask how much GPU memory do you have? You can try set `with_cp=True` in the config to save training memory.

Thank you so much! It works for InternImage-S on a 24GB memory GPU even with a bigger batch_size.
