### ISSUE TITLE
代码整理得咋样啦

### ISSUE THREAD

**Issue by 464hee** [OpenGVLab/InternImage#7]

**Comment by chenchch94** [comment]
等论文中了才可能放出来啊，早就整理好了吧

**Comment by czczup** [comment]
> > 等论文中了才可能放出来啊，早就整理好了吧
> 
> [https://arxiv.org/abs/2211.05778，已经中了吧](https://arxiv.org/abs/2211.05778%EF%BC%8C%E5%B7%B2%E7%BB%8F%E4%B8%AD%E4%BA%86%E5%90%A7)

最近几天就会放出来了

**Comment by 464hee** [comment]
> > > 等论文中了才可能放出来啊，早就整理好了吧
> > 
> > 
> > [https://arxiv.org/abs/2211.05778，已经中了吧](https://arxiv.org/abs/2211.05778%EF%BC%8C%E5%B7%B2%E7%BB%8F%E4%B8%AD%E4%BA%86%E5%90%A7)
> 
> 最近几天就会放出来了

InternImage-H 训练需要多大的显存呢，，24G以上嘛，还是48，

**Comment by czczup** [comment]
> > > > 等论文中了才可能放出来啊，早就整理好了吧
> > > 
> > > 
> > > [https://arxiv.org/abs/2211.05778，已经中了吧](https://arxiv.org/abs/2211.05778%EF%BC%8C%E5%B7%B2%E7%BB%8F%E4%B8%AD%E4%BA%86%E5%90%A7)
> > 
> > 
> > 最近几天就会放出来了
> 
> InternImage-H 训练需要多大的显存呢，，24G以上嘛，还是48，

我们用的是80G的A100

**Comment by czczup** [comment]
> 等论文中了才可能放出来啊，早就整理好了吧

检测分割代码已开源，分类马上到～

**Comment by JiahaoXia** [comment]
InternImage-H 的pretrained的模型会share吗？

**Comment by czczup** [comment]
> InternImage-H 的pretrained的模型会share吗？

暂时没有开源Huge模型的计划
