### ISSUE TITLE
BackgroundClass

### ISSUE THREAD

**Issue by aliman80** [OpenGVLab/InternImage#87]
Hi, Thank you very much for sharing your wonderful contribution. I am using this for my 5 class data where one class at index 0 is background and rest 4 are other foreground classes. I am getting better results but with 4 classes but i cant see background class . Can you guide me how to include background class . That will be great help. I tried to add background in "Classes" but its not working.

Regards

**Comment by czczup** [comment]
> Hi, Thank you very much for sharing your wonderful contribution. I am using this for my 5 class data where one class at index 0 is background and rest 4 are other foreground classes. I am getting better results but with 4 classes but i cant see background class . Can you guide me how to include background class . That will be great help. I tried to add background in "Classes" but its not working.
> 
> Regards

Hi, you should set `reduce_zero_label=False` in the config file.

**Comment by czczup** [comment]
The parameter type of `reduce_zero_label` in dataset is Boolean, which is default to False. It is used to ignore the dataset label 0. The specific method is to change label 0 to 255, and subtract 1 from the corresponding number of all the remaining labels. At the same time, set 255 as ignore index in the decode head, which means that it will not participate in the loss calculation.
