### ISSUE TITLE
ImageNet pretrained cfg not found error

### ISSUE THREAD

**Issue by jiarenyf** [OpenGVLab/InternImage#9]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/12405578/222952800-aa26a4a0-2472-4c92-8243-08e77dffcd2c.png">

**Comment by czczup** [comment]
The code for classification will be released soon.

**Comment by jiarenyf** [comment]
ok, looking forward ~

**Comment by czczup** [comment]
> ok, looking forward ~

Hi, the code for classification has been released.

**Comment by jiarenyf** [comment]
👍
